version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: neondb
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      db_username: ${db_username}
      db_password: ${db_password}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  pgdata:
